import React from "react";
import PlasticBottles from "../assets/plastic-bottles.png";
import WomanDumpingPlasticBottles from "../assets/woman-dumping-plastics.png";
import Dustbin from "../assets/dustbin.png";
import headerMain from '../assets/header-main.jpg';
import headerPic from '../assets/header-pic.jpg'
import headerPic2 from '../assets/headerpic2.jpeg'

export const Main = () => {
    return (
        <main className=" flex flex-col  items-center w-full ">
            {/* statistics */}
            <section className="flex flex-col gap-20 p-40 items-center">
            <div className="flex flex-col gap-2">
                <h3 className="text-5xl font-bold text-[#023692]">
                    What are the Statistics <span className="text-[#1164CA]">?</span>
                </h3>
                <hr className="max-w-[90px] w-full h-[4px] bg-[#3b82f6]" />
                {/* <p className="text-[#374151] text-sm font-medium">
          What is good about recycling?
        </p> */}
            </div>


            <div class="  w-full grid grid-cols-3 gap-10">
            
                 
                        <div class="bg-gray-50 flex flex-col border-b border-gray-100 px-10 py-20 text-center sm:border-0 sm:border-r shadow-lg">
                            <div class="order-2 mt-2 text-lg leading-6 font-medium text-[#1164CA]">
                                of plastic waste leaks into the ocean


                            </div>
                            <div class="order-1 text-5xl font-extrabold text-[#023692]">8M tonnes</div>
                        </div>


                        <div class="bg-gray-50 flex flex-col border-b border-gray-100 px-10 py-20 text-center sm:border-0 sm:border-r shadow-lg">
                            <div class="order-2 mt-2 text-lg leading-6 font-medium text-[#1164CA]">
                            of  plastic waste is generated by  Ghana per year


                            </div>
                            <div class="order-1 text-5xl font-extrabold text-[#023692]">840,000+ tonnes</div>
                        </div>

                        <div class="bg-gray-50 flex flex-col border-b border-gray-100 px-10 py-20 text-center sm:border-0 sm:border-r shadow-lg">
                            <div class="order-2 mt-2 text-lg leading-6 font-medium text-[#1164CA]">
                            is collected for recycling


                            </div>
                            <div class="order-1 text-5xl font-extrabold text-[#023692]">9.5%</div>
                        </div>




                        {/* <div
                            class="flex flex-col border-t border-b border-gray-100 p-6 text-center sm:border-0 sm:border-l sm:border-r">
                            <dt class="order-2 mt-2 text-lg leading-6 font-medium text-[#1164CA]">
                                of  plastic waste is generated by  Ghana per year

                            </dt>
                            <dd class="order-1 text-5xl font-extrabold text-[#023692]">840,000+ tonnes
                            </dd>
                        </div> */}
                        {/* <div class="flex flex-col border-t border-gray-100 p-6 text-center sm:border-0 sm:border-l">
                            <div class="order-2 mt-2 text-lg leading-6 font-medium text-[#1164CA]">
                                is collected for recycling
                            </div>
                            <dd class="order-1 text-5xl font-extrabold text-[#023692]">9.5%</dd>
                        </div>
                  */}
              



            </div>
            </section>

            {/* how to manage your garbage or something */}
            {/* <div className="flex flex-col gap-2">
        <h3 className="text-4xl font-bold text-[#374151]">
          Why Recycle <span className="text-[#3b82f6]">?</span>
        </h3>
        <hr className="max-w-[90px] w-full h-[4px] bg-[#3b82f6]" />
     
      </div> */}

            {/* https://gist.github.com/goodreds/3579ddfffe439457b5ef9902b5336124  */}
            <section class="bg-gray-50  w-full flex flex-col  items-center justify-center  min-h-screen px-20 ">
                <div class="flex flex-wrap items-center justify-between mb-20">
                    <h2 class="mr-10 text-5xl font-bold leading-none  text-[#023692] flex flex-col gap-2">
                       <span>Sustainable Ways to Manage Plastics</span> 
                        <hr className="max-w-[90px] w-full h-[4px] bg-[#3b82f6]" />
                    </h2>
                </div>

                <div class="flex flex-wrap -mx-4">
                    <div class="w-full max-w-full mb-8 sm:w-1/2 px-4 lg:w-1/3 flex flex-col">
                        <img src={headerMain} alt="Card img" class="object-cover object-center w-full h-48" />
                        <div class="flex flex-grow">
                            <div class="triangle"></div>
                            <div class="flex flex-col justify-between px-4 py-6 bg-white border  text">
                                <div>

                                    <a href="https://www.oursafetynet.org/2020/01/06/even-small-acts-can-have-a-ripple-effect/?gad_source=1&gclid=CjwKCAjwz42xBhB9EiwA48pT77JmtQ1geFBh35WmQ8ILTn0oTJEUrVEj_SdKJDT20hpfpPkAC38GDBoCjpgQAvD_BwE" target="blank"
                                        class="block mb-4 text-2xl font-black leading-tight hover:underline hover:text-blue-600 text-[#023692]" >
                                        How to manage plastics at home
                                    </a>
                                    <p class="mb-4 text-[#1164CA] text-lg">
                                        Even small acts can have a ripple effect Tackling plastic pollution

                                    </p>
                                </div>
                                {/* <div>
                        <a href="#"
                            class="inline-block pb-1 mt-2 text-base font-black text-blue-600 uppercase border-b border-transparent hover:border-blue-600">Read
                            More </a>
                    </div> */}
                            </div>
                        </div>
                    </div>

                    <div class="w-full max-w-full mb-8 sm:w-1/2 px-4 lg:w-1/3 flex flex-col">
                        <img
                            src={headerPic2}
                            alt="Card img"
                            class="object-cover object-center w-full h-48"
                        />
                        <div class="flex flex-grow">
                            <div class="triangle"></div>
                            <div class="flex flex-col justify-between px-4 py-6 bg-white border ">
                                <div>

                                    <a href="https://www.metabolic.nl/news/recycling-downcycling-and-the-need-for-a-circular-economy/?gad_source=1&gclid=CjwKCAjwz42xBhB9EiwA48pT7wUdUhzTRHkFdPOYLVglQ_NfRgBime8Fj3w8DanvB9DLSVDb8a_kwxoCLpsQAvD_BwE" target="blank"
                                        class="block mb-4 text-2xl font-black leading-tight hover:underline hover:text-blue-600 text-[#023692]">
                                        Why Recycle Plastics?
                                    </a>
                                    <p class="mb-4 text-[#1164CA] text-lg">
                                        When the use of a thing is unknown , abuse is inevitable. Find why Plastic Buddy is more concerned about you and your plastics.
                                    </p>
                                </div>
                                {/* <div>
                        <a href="#"
                            class="inline-block pb-1 mt-2 text-base font-black text-blue-600 uppercase border-b border-transparent hover:border-blue-600">Read
                            More -</a>
                    </div> */}
                            </div>
                        </div>
                    </div>

                    <div class="w-full max-w-full mb-8 sm:w-1/2 px-4 lg:w-1/3 flex flex-col">
                        <img
                            src={headerPic}
                            alt="Card img"
                            class="object-cover object-center w-full h-48"
                        />
                        <div class="flex flex-grow">
                            <div class="triangle"></div>
                            <div class="flex flex-col justify-between px-4 py-6 bg-white border ">
                                <div>

                                    <a href="https://blog.cleanhub.com/types-of-plastic" target="blank"
                                        class="block mb-4 text-2xl font-black leading-tight hover:underline hover:text-blue-600 text-[#023692]">
                                        Types of Plastics and How to Manage Each
                                    </a>
                                    <p class="mb-4 text-[#1164CA] text-lg">
                                        Plastic Buddy deals in all the types of plastics you know. What plastic type do you have, find out the steps n how to manage it with Plastic Buddy
                                    </p>
                                </div>
                                {/* <div>
                        <a href="#"
                            class="inline-block pb-1 mt-2 text-base font-black text-blue-600 uppercase border-b border-transparent hover:border-blue-600">Read
                            More </a>
                    </div> */}
                            </div>
                        </div>
                    </div>
                </div>
            </section>

        </main>
    );
};
